### ISSUE TITLE
An error occurred while RSpec/Capybara/SpecificFinders

### ISSUE THREAD

**Issue by ostigley** [rubocop/rubocop-rspec#1386]
Since upgrading to 2.13.1, I have experienced this error:

`An error occurred while RSpec/Capybara/SpecificFinders cop was inspecting ...<file>`

The code being inspected by rubocop is 
```ruby
    find "#deposit_and_buy_form"
```

Running rubocop -d shows:
```
Scanning <me....>/workplace/marketplace/spec/support/pages/checkout_page.rb
An error occurred while RSpec/Capybara/SpecificFinders cop was inspecting <me....>/workplace/marketplace/spec/support/pages/checkout_page.rb:61:4.
undefined method `end_pos' for nil:NilClass
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-rspec-2.13.1/lib/rubocop/cop/rspec/capybara/specific_finders.rb:80:in `offense_range'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-rspec-2.13.1/lib/rubocop/cop/rspec/capybara/specific_finders.rb:58:in `register_offense'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-rspec-2.13.1/lib/rubocop/cop/rspec/capybara/specific_finders.rb:49:in `on_id'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-rspec-2.13.1/lib/rubocop/cop/rspec/capybara/specific_finders.rb:36:in `block in on_send'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-rspec-2.13.1/lib/rubocop/cop/rspec/capybara/specific_finders.rb:38:in `find_argument'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-rspec-2.13.1/lib/rubocop/cop/rspec/capybara/specific_finders.rb:32:in `on_send'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/cop/commissioner.rb:136:in `public_send'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/cop/commissioner.rb:136:in `block (2 levels) in trigger_restricted_cops'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/cop/commissioner.rb:160:in `with_cop_error_handling'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/cop/commissioner.rb:135:in `block in trigger_restricted_cops'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/cop/commissioner.rb:134:in `each'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/cop/commissioner.rb:134:in `trigger_restricted_cops'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/cop/commissioner.rb:70:in `on_send'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-ast-1.21.0/lib/rubocop/ast/traversal.rb:153:in `on_def'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/cop/commissioner.rb:71:in `on_def'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-ast-1.21.0/lib/rubocop/ast/traversal.rb:136:in `block in on_dstr'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-ast-1.21.0/lib/rubocop/ast/traversal.rb:136:in `each'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-ast-1.21.0/lib/rubocop/ast/traversal.rb:136:in `on_dstr'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-ast-1.21.0/lib/rubocop/ast/traversal.rb:153:in `on_class'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/cop/commissioner.rb:71:in `on_class'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-ast-1.21.0/lib/rubocop/ast/traversal.rb:136:in `block in on_dstr'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-ast-1.21.0/lib/rubocop/ast/traversal.rb:136:in `each'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-ast-1.21.0/lib/rubocop/ast/traversal.rb:136:in `on_dstr'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-ast-1.21.0/lib/rubocop/ast/traversal.rb:20:in `walk'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/cop/commissioner.rb:86:in `investigate'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/cop/team.rb:155:in `investigate_partial'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/cop/team.rb:83:in `investigate'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:315:in `inspect_file'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:259:in `block in do_inspection_loop'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:293:in `block in iterate_until_no_changes'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:286:in `loop'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:286:in `iterate_until_no_changes'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:255:in `do_inspection_loop'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:138:in `block in file_offenses'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:163:in `file_offense_cache'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:137:in `file_offenses'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:128:in `process_file'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:109:in `block in each_inspected_file'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:108:in `each'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:108:in `reduce'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:108:in `each_inspected_file'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:94:in `inspect_files'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/runner.rb:47:in `run'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/cli/command.rb:11:in `run'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/cli/environment.rb:18:in `run'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/cli.rb:72:in `run_command'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/cli.rb:79:in `execute_runners'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/lib/rubocop/cli.rb:48:in `run'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/exe/rubocop:19:in `block in <top (required)>'
<me....>/.rbenv/versions/2.7.6/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.36.0/exe/rubocop:19:in `<top (required)>'
<me....>/.rbenv/versions/2.7.6/bin/rubocop:23:in `load'
<me....>/.rbenv/versions/2.7.6/bin/rubocop:23:in `<top (required)>'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:58:in `load'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:23:in `run'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/cli.rb:483:in `exec'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/cli.rb:31:in `dispatch'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/cli.rb:25:in `start'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/exe/bundle:48:in `block in <top (required)>'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
<me....>/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.12/exe/bundle:36:in `<top (required)>'
<me....>/.rbenv/versions/2.7.6/bin/bundle:23:in `load'
<me....>/.rbenv/versions/2.7.6/bin/bundle:23:in `<main>'
```

**Comment by ydah** [comment]
Thanks for the feedback.
I will check it out.
